### PR TITLE
Feature/chat

### PR DESCRIPTION
**Pull request by ArtemAng**
I've done simple chat with 2 rooms. U can try this by /chat/. When we get users i'm gonna make rooms private, add message storage and token verification

### CODE REVIEW

**Review by danielDeVita — APPROVED** [review]
looks good to me!!

**Comment by danielDeVita** [comment]
I forgot, I think you need to add another reviewer (and alexandrina too!, she is doing the merges)

**Review by FrancescaPavan — CHANGES_REQUESTED** [review]
It looks good! Just one comment, it seems that some of the changes you have are from one of @jszychowskilaba 's PRs. These shouldn't be here, make sure that only the changes relating to the chat are included in your commits.
For example changes to the README.md or .env .example and some DTOs I think

**Comment by jszychowskilaba** [comment]
*EDIT: socket have middleware for handling authentication, etc.  We have to keep this on mind

It looks good.

I see your are using mockedRooms for testing porpuse. Is the idea is to be able to assign the room id dinamically so there can be multiple chat rooms at same time ?

**Review by FrancescaPavan — APPROVED** [review]

**Pull request merged**
